### PR TITLE
Clearer exception

### PR DESCRIPTION
**Pull request by bilogic**
Throws a clearer exception message and guide the user towards adding the correct traits

### CODE REVIEW

**Comment by bilogic** [comment]
Only my last commit is for this PR, not sure why the other 2 got mixed in too

**Comment by tabuna** [comment]
Hi, if we start checking traits, we need to check more, for example, `AsSource` and` Attachable` and others. But it can silently break users' workstations if they haven't used some of the traits and their capabilities.

Therefore, I'm not sure that we should make half-hearted decisions, and full ones can violate. 
I propose to return to this when we release a new major release.

For the old commits to be missing, you need to [rebase](https://git-scm.com/docs/git-rebase)

**Comment by bilogic** [comment]
Hi, I did consider `AsSource` and `Attachable`, but the CRUD does not always call them. However, `ResourceRequest.php` always calls `->filter()`.

Anyway, my thinking was, the user will most likely miss all 3 together, so this 1 exception will (hopefully) quickly point to the root cause 1 time, then any exceptions for `AsSource` or `Attachable` and they may look at the model again.

I found it quite hard to connect the current exception `filter() does not exist...` to the model.

Perhaps we can change the message to be 

> Model must use Filterable. Consider adding `AsSource` and `Attachable` as well.

Should I rebase? Or are you able to remove it? 

Thank you.

**Comment by bilogic** [comment]
@tabuna 

I just ran into this issue again and had to check back on this issue to identify the cause. 
Haha... I really feel we should make things easier to self-discover and not have to rely on memory and docs all the time.

Have you reached a decision on this? Thank you.

**Comment by tabuna** [comment]
Let's check the value in the constructor. 
Also, make a rebase so that the changes affect only this functionality, and I will accept it.

**Comment by bilogic** [comment]
Ok, let me get it. Just to clarify, what did you mean by check in the constructor? My changes does not affect the constructor at the moment. Please let me know if I should do the checking in a different way. Thanks.

**Comment by tabuna** [comment]
I meant something like this:

```php
    /**
     * Resource constructor.
     */
    public function __construct()
    {
        $needTraits = collect(trait_uses_recursive(static::$model))->has([
            Filter::class,
        ]);

        abort_unless($needTraits, 500, 'The model must have the required traits.');
    }
```

**Comment by bilogic** [comment]
@tabuna i don't we can do it in the constructor as `$this->model()` is not ready and `static::$model` does not exist. Ok if I stick to check inside `getModelPaginationList()`?

**Pull request closed without merging**
